name: Submodule update CI

on:
  push:
    branches: [ main ]

jobs:
  submodule-update:
    name: Run when FrontOfTheHouse pointer changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Detect FrontOfTheHouse pointer change
        id: detect
        run: |
          set -euo pipefail
          prev='${{ github.event.before }}'
          cur='${{ github.sha }}'
          echo "prev=$prev"
          echo "cur=$cur"
          if [ "$prev" = "0000000000000000000000000000000000000000" ]; then
            echo "Initial commit or forced update; treating as changed"
            echo "changed=1" >> $GITHUB_OUTPUT
            exit 0
          fi
          prev_sub=$(git ls-tree $prev FrontOfTheHouse 2>/dev/null | awk '{print $3}') || true
          cur_sub=$(git ls-tree $cur FrontOfTheHouse 2>/dev/null | awk '{print $3}') || true
          echo "prev_sub=$prev_sub"
          echo "cur_sub=$cur_sub"
          if [ "$prev_sub" != "$cur_sub" ]; then
            echo "changed=1" >> $GITHUB_OUTPUT
          else
            echo "changed=0" >> $GITHUB_OUTPUT
          fi

      - name: Stop if submodule didn't change
        if: steps.detect.outputs.changed == '0'
        run: |
          echo "FrontOfTheHouse pointer did not change in this push; skipping build."

      - name: Setup Node.js
        if: steps.detect.outputs.changed == '1'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        if: steps.detect.outputs.changed == '1'
        working-directory: FrontOfTheHouse
        run: npm ci

      - name: Build frontend
        if: steps.detect.outputs.changed == '1'
        working-directory: FrontOfTheHouse
        run: npm run build

      - name: Copy frontend build to wwwroot
        if: steps.detect.outputs.changed == '1'
        run: |
          rm -rf wwwroot/* || true
          cp -R FrontOfTheHouse/dist/sandwichUi/* wwwroot/

      - name: Setup .NET
        if: steps.detect.outputs.changed == '1'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Publish backend
        if: steps.detect.outputs.changed == '1'
        run: dotnet publish BackOfTheHouse.csproj -c Release -o out/publish
